# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-29 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'liked'), ('d', 'dislike'), ('u', 'undecided')], default='undecided', max_length=10),
        ),
    ]
